apiVersion: skaffold/v2beta29
kind: Config
deploy:
  helm:
    releases:
      - name: dapr
        repo: https://dapr.github.io/helm-charts/
        remoteChart: dapr
        version: "1.8"
        setValues:
          "global.mtls.enabled": false
      - name: redis
        repo: https://charts.bitnami.com/bitnami
        remoteChart: redis
        setValues:
          architecture: standalone
      - name: distributed-calculator
        chartPath: distributed-calculator
        overrides: # override Values.yaml
          replicaCount: 1
portForward:
  - resourceType: service
    resourceName: calculator-front-end
    namespace: default
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: zipkin
    namespace: default
    port: 9411
    localPort: 9411
