# this file is from https://github.com/dapr/quickstarts (under MIT license).
# https://github.com/dapr/quickstarts/blob/master/distributed-calculator/deploy/appconfig.yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
